name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme ParkInBordeaux -project ParkInBordeaux.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0' | xcpretty && exit ${PIPESTATUS[0]}
