name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
      
    - name: Run build
      run: xcodebuild clean build test -project ParkInBordeaux.xcodeproj -scheme "ParkInBordeaux" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13,OS=15.2" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
