name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests_IOS16:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 14
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version
    - name: Run tests iOS16
      run: xcodebuild test -scheme ParkInBordeaux -project ParkInBordeaux.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 13,OS=16.0'
  run_tests_IOS15:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode 13
      run: sudo xcode-select -switch /Applications/Xcode_14.0.app && /usr/bin/xcodebuild -version
    - name: Run tests iOS15
      run: xcodebuild test -scheme ParkInBordeaux -project ParkInBordeaux.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2'
